# Site settings
title: Leon
description: "Binary Exploitation, Evasion, Packers, Covert comms."
url: "http://leonyya.github.io"
author:
  name: "Luis Leon"
  email: ""
  url: "http://leonyya.github.io"
  twitter_username: theLeonyya
  github_username: Leonyya

# Build settings
baseurl: # Change this to your relative path (ex: /blog), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:year/:title:output_ext
#paginate: 8
#paginate_path: /page:num/

#Default values
defaults:
  - scope:
      path: "_assets"
    values:
      image: true
#  -
#    scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "post"

# Custom variables
version: "1.1.0"

# Options
#custom_header: false
#custom_nav_footer: false
#reverse: false

gems: 
    - jekyll-sitemap
